/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quizmain;
import static Quizmain.Question2.points;
import javax.swing.JOptionPane;
/**
 *
 * @author Acer Aspire 7
 */
public class Question3 extends javax.swing.JFrame {

    /**
     * Creates new form Question3
     */
    public Question3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        four = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        one = new javax.swing.JCheckBox();
        two = new javax.swing.JCheckBox();
        three = new javax.swing.JCheckBox();
        Oneanswer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        points = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Question 3:-");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 40));

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setForeground(new java.awt.Color(51, 51, 255));
        four.setText("Vincent van Gogh");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel3.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Who painted the Mona Lisa?");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, 30));

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setForeground(new java.awt.Color(51, 51, 255));
        one.setText("Leonardo da Vinci");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel3.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setForeground(new java.awt.Color(51, 51, 255));
        two.setText("Johannes Vermeer");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel3.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setForeground(new java.awt.Color(51, 51, 255));
        three.setText("Sandro Botticelli");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel3.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        Oneanswer.setBackground(new java.awt.Color(255, 255, 255));
        Oneanswer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Oneanswer.setForeground(new java.awt.Color(102, 51, 255));
        jPanel3.add(Oneanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 300, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Correct Answer:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 40));

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, 40));

        points.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        points.setForeground(new java.awt.Color(51, 51, 255));
        points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsActionPerformed(evt);
            }
        });
        jPanel3.add(points, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 40, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Points");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 60, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(one.isSelected() || two.isSelected() || three.isSelected() || four.isSelected()){

            this.dispose();
            new Final().setVisible(true);
        }
        else{
            this.setVisible(true);
            JOptionPane.showMessageDialog(null,"Please select one option !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        
         if(one.isSelected()){
             three.setVisible(false);
             two.setVisible(false);
             four.setVisible(false);
            one.setSelected(true);
            two.setSelected(false);
        three.setSelected(false);
        four.setSelected(false);
            Oneanswer.setText("Correct");
            if(Question2.points.getText().startsWith("1")){
             points.setText("2");
             }
             else if(Question2.points.getText().startsWith("0")){
             points.setText("1");
                     
        }
             else if(Question2.points.getText().startsWith("2"))
             {
                 points.setText("3");
             }
        }
    }//GEN-LAST:event_oneActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         if(three.isSelected()) {
             one.setVisible(false);
             two.setVisible(false);
             four.setVisible(false);
              three.setSelected(true);
              one.setSelected(false);
        two.setSelected(false);
        four.setSelected(false);
                Oneanswer.setText("Wrong! Correct answer is Leonardo da Vinci ");
               if(Question2.points.getText().startsWith("1")){
             points.setText("1");
             }
             else if(Question2.points.getText().startsWith("0")){
             points.setText("0");
                     
        }
             else if(Question2.points.getText().startsWith("2"))
             {
                 points.setText("2");
             }
            
        }
    }//GEN-LAST:event_threeActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
          if(two.isSelected()) {
              one.setVisible(false);
             three.setVisible(false);
             four.setVisible(false);
                two.setSelected(true);
                one.setSelected(false);
        three.setSelected(false);
        four.setSelected(false);
                Oneanswer.setText("Wrong !Correct answer is Leonardo da Vinci ");
                if(Question2.points.getText().startsWith("1")){
             points.setText("1");
             }
             else if(Question2.points.getText().startsWith("0")){
             points.setText("0");
                     
        }
             else if(Question2.points.getText().startsWith("2"))
             {
                 points.setText("2");
             }
            
        }
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
         if(four.isSelected()) {
             one.setVisible(false);
             two.setVisible(false);
             three.setVisible(false);
              four.setSelected(true);
              two.setSelected(false);
        three.setSelected(false);
        one.setSelected(false);
                Oneanswer.setText("Wrong! Correct answer is Leonardo da Vinci ");
               if(Question2.points.getText().startsWith("1")){
             points.setText("1");
             }
             else if(Question2.points.getText().startsWith("0")){
             points.setText("0");
                     
        }
             else if(Question2.points.getText().startsWith("2"))
             {
                 points.setText("2");
             }
            
        }
    }//GEN-LAST:event_fourActionPerformed

    private void pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_pointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Oneanswer;
    private javax.swing.JCheckBox four;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox one;
    public static javax.swing.JTextField points;
    private javax.swing.JCheckBox three;
    private javax.swing.JCheckBox two;
    // End of variables declaration//GEN-END:variables
}
