/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quizmain;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer Aspire 7
 */
public class Question2 extends javax.swing.JFrame {

    /**
     * Creates new form Question2
     */
    public Question2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        three = new javax.swing.JCheckBox();
        four = new javax.swing.JCheckBox();
        two = new javax.swing.JCheckBox();
        one = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        points = new javax.swing.JTextField();
        Oneanswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 100, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Correct Answer:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        three.setForeground(new java.awt.Color(102, 102, 255));
        three.setText("China");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel1.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 30));

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        four.setForeground(new java.awt.Color(102, 102, 255));
        four.setText("India");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel1.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, 30));

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        two.setForeground(new java.awt.Color(102, 102, 255));
        two.setText("France");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel1.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        one.setForeground(new java.awt.Color(102, 102, 255));
        one.setText("Japan");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel1.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Which country is brie cheese originally from?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Question 2:-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Points");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 60, 20));

        points.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        points.setForeground(new java.awt.Color(51, 51, 255));
        points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsActionPerformed(evt);
            }
        });
        jPanel1.add(points, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 40, -1));

        Oneanswer.setBackground(new java.awt.Color(255, 255, 255));
        Oneanswer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Oneanswer.setForeground(new java.awt.Color(102, 51, 255));
        jPanel1.add(Oneanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        if(three.isSelected()) {
             one.setVisible(false);
             two.setVisible(false);
             four.setVisible(false);
            three.setSelected(true);
            one.setSelected(false);
            two.setSelected(false);
            four.setSelected(false);
            Oneanswer.setText("Wrong! Correct answer is France ");
                        if(Question1.points.getText().startsWith("1")){
             points.setText("1");
            }
             else if(Question1.points.getText().startsWith("0")){
             points.setText("0");
           
        }

        }
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        if(four.isSelected()) {
             one.setVisible(false);
             three.setVisible(false);
             two.setVisible(false);
            four.setSelected(true);
            two.setSelected(false);
            three.setSelected(false);
            one.setSelected(false);
            Oneanswer.setText("Wrong! Correct answer is France ");
                         if(Question1.points.getText().startsWith("1")){
             points.setText("1");
            }
             else if(Question1.points.getText().startsWith("0")){
             points.setText("0");
           
        }

        }
        one.setSelected(false);
        three.setSelected(false);
        two.setSelected(false);
    }//GEN-LAST:event_fourActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        if(two.isSelected()) {
             one.setVisible(false);
             three.setVisible(false);
             four.setVisible(false);
            two.setSelected(true);
            one.setSelected(false);
            three.setSelected(false);
            four.setSelected(false);
            Oneanswer.setText("Correct  ");
             if(Question1.points.getText().startsWith("1")){
             points.setText("2");
             }
             else if(Question1.points.getText().startsWith("0")){
             points.setText("1");
                     
        }
           
        }
       
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:

        if(one.isSelected()){
            one.setSelected(true);
             two.setVisible(false);
             three.setVisible(false);
             four.setVisible(false);
            two.setSelected(false);
            three.setSelected(false);
            four.setSelected(false);
            Oneanswer.setText("Wrong! Correct answer is France");
             if(Question1.points.getText().startsWith("1")){
             points.setText("1");
            }
             else if(Question1.points.getText().startsWith("0")){
             points.setText("0");
           
        }
       
        two.setSelected(false);
        three.setSelected(false);
        four.setSelected(false);

    }//GEN-LAST:event_oneActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(one.isSelected() || two.isSelected() || three.isSelected() || four.isSelected()){
            // this.setVisible(false);
             this.dispose();
        new Question3().setVisible(true);
        }
        else{
            
            JOptionPane.showMessageDialog(null,"Please select one option !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsActionPerformed
        // TODO add your handling code here:
        if(Question1.points.getText().equals(1)){
             points.setText("4");
        }
      
    }//GEN-LAST:event_pointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Oneanswer;
    private javax.swing.JCheckBox four;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox one;
    public static javax.swing.JTextField points;
    private javax.swing.JCheckBox three;
    private javax.swing.JCheckBox two;
    // End of variables declaration//GEN-END:variables
}
